### ISSUE TITLE
Not functioning

### ISSUE THREAD

**Issue by danirabbit** [elementary/pantheon-agent-geoclue2#41]
In Odin, I'm not seeing the agent appear at all when apps request location info

**Comment by davidmhewitt** [comment]
This is because Geoclue upstream decided that anything that wasn't sandboxed could potentially be lying about its desktop ID, so everything may as well be authorized without asking the agent.

**Comment by davidmhewitt** [comment]
Additionally, it looks like turning location services off altogether via the agent isn't even a thing anymore in the version of geoclue we have. It looks like that was fixed upstream recently, but there hasn't been a release for that commit so it definitely won't be in focal.

So aside from the dialog not appearing, the location services on/off switch also does nothing, because everything that isn't sandboxed is implicitly allowed access to geoclue.

We could pull the patches into os-patches to at least allow the on/off switch to work again. We could also in theory revert some of the changes that would allow the agent to appear again for non-sandboxed apps too, but it's clear there's no interest in having this upstream and it's true that any app can come along and present `firefox` or `gnome-colour-panel` as their desktop ID to geoclue and automatically be granted access since those things are "trusted". So the dialog appearing was always a bit of a false sense of security.

**Comment by danrabbit** [comment]
Wow that's rough! I guess they aren't considering non-technical enforcement like app reviews

Theoretically this isn't a big deal as long as we get AppCenter running on Flatpak before release, I suppose

**Comment by danrabbit** [comment]
It sounds like from our discussion in standup that the path forward here is to try to build a newer GeoClue that fixes the switch

**Comment by danrabbit** [comment]
There is an issue in Ubuntu here marked as high priority: https://gitlab.freedesktop.org/geoclue/geoclue/-/releases/2.5.7

It is now also confirmed, since I marked as affected me.

I'm going to try pursuing an SRU with Ubuntu first before we do our own backport

**Comment by danrabbit** [comment]
Ubuntu desktop team is gonna bring up the SRU at their next meeting :tada:

**Comment by danrabbit** [comment]
Alright so upstream isn't pursuing the SRU anymore, but we now have 2.5.7 building in os-patches. I'm not seeing a difference in behavior here, so we must have to make some changes still.

Something I noticed is that when running the agent and toggling location services we get a warning:

```
(pantheon-agent-geoclue2:6685): GLib-GObject-WARNING **: 15:22:42.820: g_object_notify: object class 'AgAgent' has no property named 'max-accuracy-level'
```

But it looks like we get the same warning on 5.1.7 so it's probably a red herring

**Comment by danirabbit** [comment]
Closing since this is working with older GeoClue if apps build against it (as tested in Atlas) and we're working on replacing this with portals anyways
